# SGeOL Docker 
# Build: docker-compose pull
# Run: docker-compose up 
# Run in daemon: docker-compose up -d

keyrock:
     build: keyrock
     hostname: keyrock
     container_name: keyrock
     expose:
         - "5000"
         - "8000"
     ports:
         - "5000:5000"
         - "8000:8000"
         
# pepproxy:
#      build: fiware-pep-proxy
#      hostname: pepproxy
#      container_name: pepproxy
#      expose:
#          - "80"
#      ports:
#          - "80:80"
#      links:
#          - authzforce
#          - keyrock 
